# SPDX-FileCopyrightText: 2021 Dylan Van Assche <me@dylanvanassche.be>
# SPDX-License-Identifier: GPL-3.0-or-later

image: alpine:edge
stages:
  - test
  - package

test:
  stage: test
  before_script:
    - apk add py3-pytest py3-dbus py3-mypy
  script:
    - pytest
    - mypy obex_capabilities

package:
  stage: package
  variables:
    DEVICEINFO_PATH: "./tests/data/deviceinfo"
    OS_RELEASE_PATH: "./tests/data/os-release"
    MACHINE_ID_PATH: "./tests/data/machine-id"
  before_script:
    - apk add py3-setuptools py3-pytest py3-dbus
  script:
    - python3 setup.py install
    - obex-capabilities
